IT_SERVICES_COMPANIES = {
    "tcs",
    "tata consultancy",
    "tata consultancy services",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "mindtree",
    "mphasis",
    "hexaware",
    "hexaware technologies",
    "ltimindtree",
    "tech mahindra",
    "hcl technologies",
    "hcltech",
    "hcl",
    "hcl group",
    "ibm global",
    "ibm",
    "atos",
    "dxc technology",
    "epam",
    "epam systems",
    "niit technologies",

    # Additional companies, sources:https://www.ambitionbox.com/it-services-and-consulting-companies-in-india
    "wns",
    "digitide solutions",
    "coforge",
    "optum global solutions",
    "l&t technology services",
    "ltts",
    "eclerx",
    "virtusa",
    "virtusa consulting services",
    "globallogic",
    "ust",
    "ust global",
    "bosch global software technologies",
    "cgi",
    "cgi inc",
    "ntt data",
    "cyient",
    "persistent systems",
    "itc infotech",
    "nagarro",
    "eviden",
    "ey global delivery services",
    "ey gds",
    "hewlett packard enterprise",
    "hpe",
    "carelon global solutions",
    "publicis sapient",
    "sapient",
    "kyndryl",
    "birlasoft",
    "synechron",
    "societe generale global solution centre",
    "quest global",
    "tata elxsi",
    "zensar technologies",
    "cms it services",
    "fujitsu",
    "vvdn technologies",
    "movate",
    "photon interactive",
    "datamatics global services",
    "rmsi",
    "newgen software technologies",
    "newgen",
    "3i infotech",
    "capgemini engineering",
    "cybage",
    "straive",
    "sopra steria",
    "kochartech",
    "xoriant",
    "team computers",
    "valuelabs",
    "sify technologies",
    "mercedes-benz research and development india",
    "mbrdi",
    "jio platforms",
    "ntt data business solutions",
    "infinite computer solutions",
    "citiustech",
    "yash technologies",
    "hsbc electronic data processing",
    "ncr voyix",
    "telus digital",
    "microland",
    "htc global services",
    "neosoft",
    "iris software",
    "tekwissen",
    "axa global business services",
    "ss&c technologies",
    "ss&c",
    "orange business",
}