FUSION_BM25_WEIGHT  = 0.35
FUSION_DENSE_WEIGHT = 0.65

PRELIM_FUSION_WEIGHT       = 0.45   
PRELIM_STRUCTURAL_WEIGHT   = 0.43   
PRELIM_AVAILABILITY_WEIGHT = 0.12   

FINAL_PRELIM_WEIGHT = 0.70   
FINAL_CE_WEIGHT     = 0.30   

SCORE_PENALTY_MULTIPLIER   = 0.82   
SCORE_CAP_MAX              = 0.74   
SCORE_CAP_EXP_FIT_FLOOR    = 0.50   
SCORE_CAP_ML_RECENCY_YEARS = 2.0    

NOTICE_SCORE_0_15   = 1.00
NOTICE_SCORE_16_30  = 0.90   
NOTICE_SCORE_31_60  = 0.55   
NOTICE_SCORE_61_90  = 0.30   
NOTICE_SCORE_91_120 = 0.18   
NOTICE_SCORE_120P   = 0.08   

assert abs(FUSION_BM25_WEIGHT + FUSION_DENSE_WEIGHT - 1.0) < 1e-9, \
    "Fusion weights must sum to 1.0"
assert abs(PRELIM_FUSION_WEIGHT + PRELIM_STRUCTURAL_WEIGHT + PRELIM_AVAILABILITY_WEIGHT - 1.0) < 1e-9, \
    "Prelim weights must sum to 1.0"
assert abs(FINAL_PRELIM_WEIGHT + FINAL_CE_WEIGHT - 1.0) < 1e-9, \
    "Final weights must sum to 1.0"
assert 0.0 < SCORE_CAP_MAX < 1.0, \
    "Score cap must be in (0, 1)"

NARRATIVE_SCORE_WEIGHT   = 0.30   
COMPANY_FIT_WEIGHT       = 0.24   
EXPERIENCE_FIT_WEIGHT    = 0.17   
LOCATION_FIT_WEIGHT      = 0.15   
TRAJECTORY_SCORE_WEIGHT  = 0.04   
SALARY_FIT_WEIGHT        = 0.02   

_STRUCTURAL_BASE = (
    NARRATIVE_SCORE_WEIGHT
    + COMPANY_FIT_WEIGHT
    + LOCATION_FIT_WEIGHT
    + EXPERIENCE_FIT_WEIGHT
    + TRAJECTORY_SCORE_WEIGHT
    + SALARY_FIT_WEIGHT
)
assert abs(_STRUCTURAL_BASE - 0.92) < 1e-9, \
    f"Structural base weights must sum to 0.92, got {_STRUCTURAL_BASE}"